services:
  postgres:
    image: postgres
    user: root
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
volumes:
  data: {}
