name: Publish APIs
on:
    workflow_dispatch:
jobs:
  build-order-api-java:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -f order-api-java/pom.xml clean verify
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: order-api-java-artifacts
        path: |
          order-api-java/target/openapi/openapi.json
          order-api-java/src/docs

  build-template-api-nestjs:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: api
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Use Node.js
      uses: actions/setup-node@main
      with:
        node-version: '16'
    - name: Install dependencies
      run: cd template-api-nestjs && npm install
    - name: Build NestJS project
      run: cd template-api-nestjs && npm run build
    - name: Start the application
      run: cd template-api-nestjs && ./startup.ci.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: template-api-nestjs-artifacts
        path: |
          template-api-nestjs/openapi/swagger.json
          template-api-nestjs/docs
      

  build-users-api-express-tsoa:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Use Node.js
      uses: actions/setup-node@main
      with:
        node-version: '16'
    - name: Install dependencies
      run: cd users-api-express-tsoa && npm install
    - name: Build Express project with TSOA
      run: cd users-api-express-tsoa && npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: users-api-express-tsoa-artifacts
        path: |
          users-api-express-tsoa/build/openapi/swagger.json
          users-api-express-tsoa/src/docs

  publish-api:
    needs: [build-order-api-java, build-template-api-nestjs, build-users-api-express-tsoa]
    runs-on: ubuntu-latest
    container:
      image: node:latest
    env:
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORGID }}
      ANYPOINT_HOST: ${{ secrets.ANYPOINT_HOST }}
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Download order-api-java artifacts
      uses: actions/download-artifact@main
      with:
        name: order-api-java-artifacts
        path: order-api-java
    - name: Download template-api-nestjs artifacts
      uses: actions/download-artifact@main
      with:
        name: template-api-nestjs-artifacts
        path: template-api-nestjs
    - name: Download users-api-express-tsoa artifacts
      uses: actions/download-artifact@main
      with:
        name: users-api-express-tsoa-artifacts
        path: users-api-express-tsoa
    - name: Install api-catalog-cli
      run: npm install -g api-catalog-cli@latest
    - name: Publish API to Anypoint Exchange
      run: |
        api-catalog publish-asset --organization="$ANYPOINT_ORG_ID" --client_id="$ANYPOINT_CLIENT_ID" --client_secret="$ANYPOINT_CLIENT_SECRET" --host="$ANYPOINT_HOST"